RAID = [
    "MADARCHOD TERI MAA KI CHUT ME GHUTKA KHAAKE THOOK DUNGI 🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEEN NHI HAI KYA? 9 MAHINE RUK SAGI VAHEEN DETA HU 🤣🤣🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA K BHOSDE ME AEROPLANEPARK KARKE UDAAN BHAR DUGA ✈️🛫✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME SUTLI BOMB FOD DUNGA TERI MAA KI JHAATE JAL KE KHAAK HO JAYEGI💣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKI CHUT ME SCOOTER DAAL DUGA👅✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT KAKTE 🤱 GALI KE KUTTO 🦮 ME BAAT DUNGA PHIR 🍞 BREAD KI TARH KHAYENGE WO TERI MAA KI CHUT✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "DUDH HILAAUNGA TERI VAHEEN KE UPR NICHE 🆙🆒😙✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME ✋ HATTH DALKE 👶 BACCHE NIKAL DUNGA 😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHN KI CHUT ME KELE KE CHILKE 🍌🍌😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BHEN KI CHUT ME USERBOT LAGAAUNGA SASTE SPAM KE CHODE",
    "TERI VAHEEN DHANDHE VAALI 😋😛✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE BHOSDE ME AC LAGA DUNGA SAARI GARMI NIKAL JAAYEGI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEEN KO HORLICKS PEELAUNGA MADARCHOD😚✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI GAAND ME SARIYA DAAL DUNGA MADARCHOD USI SARIYE PR TANG KE BACHE PAIDA HONGE 😱😱✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO KOLKATA VAALE JITU BHAIYA KA LUND MUBARAK 🤩🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MUMMY KI FANTASY HU LAWDE, TU APNI BHEN KO SMBHAAL 😈😈✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERA PEHLA BAAP HU MADARCHOD ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEEN KE BHOSDE ME XVIDEOS.COM CHALA KE MUTH MAARUNGA 🤡😹✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KA GROUP VAALON SAATH MILKE GANG BANG KRUNGA🙌🏻☠️✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND ",
    "TERI ITEM KI GAAND ME LUND DAALKE,TERE JAISA EK OR NIKAAL DUNGA MADARCHOD🤘🏻🙌🏻☠️ ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "AUKAAT ME REH VRNA GAAND ME DANDA DAAL KE MUH SE NIKAAL DUNGA SHARIR BHI DANDE JESA DIKHEGA 🙄🤭🤭✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MUMMY KE SAATH LUDO KHELTE KHELTE USKE MUH ME APNA LODA DE DUNGA☝🏻☝🏻😬✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEEN KO APNE LUND PR ITNA JHULAAUNGA KI JHULTE JHULTE HI BACHA PAIDA KR DEGI👀👯 ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT MEI BATTERY LAGA KE POWERBANK BANA DUNGA 🔋 🔥🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT MEI C++ STRING ENCRYPTION LAGA DUNGA BAHTI HUYI CHUT RUK JAYEGIIII😈🔥😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE GAAND MEI JHAADU DAL KE MOR 🦚 BANA DUNGAA 🤩🥵😱✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI CHUT KI CHUT MEI SHOULDERING KAR DUNGAA HILATE HUYE BHI DARD HOGAAA😱🤮👺✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO REDI PE BAITHAL KE USSE USKI CHUT BILWAUNGAA 💰 😵🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BHOSDIKE TERI MAA KI CHUT MEI 4 HOLE HAI UNME MSEAL LAGA BAHUT BAHETI HAI BHOFDIKE👊🤮🤢🤢✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KI CHUT MEI BARGAD KA PED UGA DUNGAA CORONA MEI SAB OXYGEN LEKAR JAYENGE🤢🤩🥳✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT MEI SUDO LAGA KE BIGSPAM LAGA KE 9999 FUCK LAGAA DU 🤩🥳🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEN KE BHOSDIKE MEI BESAN KE LADDU BHAR DUNGA🤩🥳🔥😈✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT KHOD KE USME CYLINDER ⛽️ FIT KARKE USMEE DAL MAKHANI BANAUNGAAA🤩👊🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT MEI SHEESHA DAL DUNGAAA AUR CHAURAHE PE TAANG DUNGA BHOSDIKE😈😱🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT MEI CREDIT CARD DAL KE AGE SE 500 KE KAARE KAARE NOTE NIKALUNGAA BHOSDIKE💰💰🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE SATH SUAR KA SEX KARWA DUNGAA EK SATH 6-6 BACHE DEGI💰🔥😱✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KI CHUT MEI APPLE KA 18W WALA CHARGER 🔥🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KI GAAND MEI ONEPLUS KA WRAP CHARGER 30W HIGH POWER 💥😂😎✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KI CHUT KO AMAZON SE ORDER KARUNGA 10 rs MEI AUR FLIPKART PE 20 RS MEI BECH DUNGA🤮👿😈🤖✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI BADI BHUND ME ZOMATO DAL KE SUBWAY KA BFF VEG SUB COMBO [15cm , 16 inches ] ORDER COD KRVAUNGA OR TERI MAA JAB DILIVERY DENE AYEGI TAB USPE JAADU KRUNGA OR FIR 9 MONTH BAAD VO EK OR FREE DILIVERY DEGI🙀👍🥳🔥",
    "TERI BHEN KI CHUT KAALI🙁🤣💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME CHANGES COMMIT KRUGA FIR TERI BHEEN KI CHUT AUTOMATICALLY UPDATE HOJAAYEGI🤖🙏🤔✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAUSI KE BHOSDE MEI INDIAN RAILWAY 🚂💥😂✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TU TERI BAHEN TERA KHANDAN SAB BAHEN KE LAWDE RANDI HAI RANDI 🤢✅🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KI CHUT MEI IONIC BOND BANA KE VIRGINITY LOOSE KARWA DUNGA USKI 📚 😎🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI RANDI MAA SE PUCHNA BAAP KA NAAM BAHEN KE LODEEEEE 🤩🥳😳✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TU AUR TERI MAA DONO KI BHOSDE MEI METRO CHALWA DUNGA MADARXHOD 🚇🤩😱🥶✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO ITNA CHODUNGA TERA BAAP BHI USKO PAHCHANANE SE MANA KAR DEGA😂👿🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KE BHOSDE MEI HAIR DRYER CHALA DUNGAA💥🔥🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT MEI TELEGRAM KI SARI RANDIYON KA RANDI KHANA KHOL DUNGAA👿🤮😎✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ALEXA DAL KEE DJ BAJAUNGAAA 🎶 ⬆️🤩💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE BHOSDE MEI GITHUB DAL KE APNA BOT HOST KARUNGAA 🤩👊👤😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KA VPS BANA KE 24*7 BASH CHUDAI COMMAND DE DUNGAA 🤩💥🔥🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MUMMY KI CHUT MEI TERE LAND KO DAL KE KAAT DUNGA MADARCHOD 🔪😂🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUN TERI MAA KA BHOSDA AUR TERI BAHEN KA BHI BHOSDA 👿😎👊✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TUJHE DEKH KE TERI RANDI BAHEN PE TARAS ATA HAI MUJHE BAHEN KE LODEEEE 👿💥🤩🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUN MADARCHOD JYADA NA UCHAL MAA CHOD DENGE EK MIN MEI ✅🤣🔥🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "APNI AMMA SE PUCHNA USKO US KAALI RAAT MEI KAUN CHODNEE AYA THAAA! TERE IS PAPA KA NAAM LEGI 😂👿😳✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TOHAR BAHIN CHODU BBAHEN KE LAWDE USME MITTI DAL KE CEMENT SE BHAR DU 🏠🤢🤩💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TUJHE AB TAK NAHI SMJH AYA KI MAI HI HU TUJHE PAIDA KARNE WALA BHOSDIKEE APNI MAA SE PUCH RANDI KE BACHEEEE 🤩👊👤😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE BHOSDE MEI SPOTIFY DAL KE LOFI BAJAUNGA DIN BHAR 😍🎶🎶💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KA NAYA RANDI KHANA KHOLUNGA CHINTA MAT KAR 👊🤣🤣😳✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERA BAAP HU BHOSDIKE TERI MAA KO RANDI KHANE PE CHUDWA KE US PAISE KI DAARU PEETA HU 🍷🤩🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BAHEN KI CHUT MEI APNA BADA SA LODA GHUSSA DUNGAA KALLAAP KE MAR JAYEGI 🤩😳😳🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TOHAR MUMMY KI CHUT MEI PURI KI PURI KINGFISHER KI BOTTLE DAL KE TOD DUNGA ANDER HI 😱😂🤩✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO ITNA CHODUNGA KI SAPNE MEI BHI MERI CHUDAI YAAD KAREGI RANDI 🥳😍👊💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MUMMY AUR BAHEN KO DAUDA DAUDA NE CHODUNGA UNKE NO BOLNE PE BHI LAND GHUSA DUNGA ANDER TAK 😎😎🤣🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MUMMY KI CHUT KO ONLINE OLX PE BECHUNGA AUR PAISE SE TERI BAHEN KA KOTHA KHOL DUNGA 😎🤩😝😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE BHOSDA ITNA CHODUNGA KI TU CAH KE BHI WO MAST CHUDAI SE DUR NHI JA PAYEGAA 😏😏🤩😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUN BE RANDI KI AULAAD TU APNI BAHEN SE SEEKH KUCH KAISE GAAND MARWATE HAI😏🤬🔥💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KA YAAR HU MEI AUR TERI BAHEN KA PYAAR HU MEI AJA MERA LAND CHOOS LE 🤩🤣💥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BHEN KI CHUT ME USERBOT LAGAAUNGA SASTE SPAM KE CHODE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI GAAND ME SARIYA DAAL DUNGA MADARCHOD USI SARIYE PR TANG KE BACHE PAIDA HONGE 😱😱✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME ✋ HATTH DALKE 👶 BACCHE NIKAL DUNGA 😍✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHN KI CHUT ME KELE KE CHILKE 🤤🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME SUTLI BOMB FOD DUNGA TERI MAA KI JHAATE JAL KE KHAAK HO JAYEGI💣💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEEN KO HORLICKS PEELAKE CHODUNGA MADARCHOD😚✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI ITEM KI GAAND ME LUND DAALKE,TERE JAISA EK OR NIKAAL DUNGA MADARCHOD😆🤤💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI VAHEEN KO APNE LUND PR ITNA JHULAAUNGA KI JHULTE JHULTE HI BACHA PAIDA KR DEGI 💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
]

RiZoeLX = [1517994352, 2086101519, 136817688]

REPLYRAID = [
    "MADARCHOD DOLLY SE LEGA PANGA HOJAYGA NANGA",
    "BHOSDIKE ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "LAAAWEEE KE BAAAAAL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MADRCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND..",
    "TERI MA KI CHUT MARI DOLLY NE..",
    "LWDE KE BAAALLL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND.",
    "MACHAR KI JHAAT KE BAAALLLL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MA KI CHUT M DU TAPA TAP?✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MA KA BHOSDAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BHN SBSBE BDI RANDI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND.",
    "TERI MA OSSE BADI RANDDDDD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERA BAAP CHKAAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KITNI CHODU TERI MA AB OR✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND..",
    "TERI MA CHOD DI HM NE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MA KE STH REELS BNEGA ROAD PEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MA KI CHUT EK DAM TOP SEXY✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "LUND KE CHODE TU KEREGA TYPIN✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SPEED PKD LWDEEEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BAAP KI SPEED MTCH KRRR✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "LWDEEE #DOLLY OP",
    "PAPA KI SPEED MTCH NHI HO RHI KYA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ALE ALE MELA BCHAAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHUD GYA PAPA SEEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KISAN KO KHODNA OR #DOLLY KO CHODNA NHI SIKHATE",
    "SALE RAPEKL KRDKA TERA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HAHAHAAAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KIDSSSS ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MA CHUD GYI AB FRAR MT HONA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "YE LDNGE BAPP SE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KIDSSS FRAR HAHAHH✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BHEN KE LWDE SHRM KR✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KITNI GLIYA PDWEGA APNI MA KO✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "NALLEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SHRM KR #DOLLY NE CHOD DIYA TUMKO",
    "MERE LUND KE BAAAAALLLLL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RNDI KE LDKEEEEEEEEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KIDSSSSSSSSSSSS✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Apni gaand mein muthi daal✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "#ROYAL KA lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BETE TERI MA SBSE BDI RAND✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GLTI KRDI TUJW PAIDA KRKE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SPEED PKDDD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Gaand main LWDA DAL LE APNI MERAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Gaand mein bambu DEDUNGAAAAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GAND FTI KE BALKKK✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "#ROYAL KA lund teri gaand main",
    "Jhaant ke pissu-✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MA KI KALI CHUT✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Khotey ki aulda✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Kutte ka awlat✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Kutte ki jat✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Kutte ke tatte✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Lavde ke bal✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "muh mei lele✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Lund Ke Pasine✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MERE LWDE KE BAAAAALLL✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "HAHAHAAAAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHUD GYAAAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Randi khanE KI ULADDD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Sadi hui gaand✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Teri gaand main kute ka lund✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Teri maa ka bhosda✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Teri maa ki chut✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Tere gaand mein keede paday✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Ullu ke pathe✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SUNN MADERCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KA BHOSDA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BEHEN K LUND✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KA CHUT KI CHTNIIII✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "GAANDU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHUTIYA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "SAMJHAA LAWDE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "YA DU TERE GAAND ME TAPAA TAP��✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI BEHEN MERA ROZ LETI HAI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO LEKAR MAI FARAR✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RANIDIII✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "BACHEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHODU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RANDI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RANDI KE PILLE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERIIIII MAAA KO BHEJJJ✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERAA BAAAAP HU✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Teri maa KO SARAK PE LETAA DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Teri maa KI CHUT MÉ KAALI MITCH✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA SASTI RANDI HAI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAA RANDI HAI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KAAA BHOSDAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME LAPTOP✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "Teri maa RANDI HAI✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERI MAA KAA BHOSDA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MERAAA LUND PAKAD LE MADARCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "CHUP TERI MAA AKAA BHOSDAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERIII MAA KAA BJSODAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "MADARXHODDD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERIUUI MAAA KAA BHSODAAA✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "NIKAL MADARCHOD✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "RANDI KE BACHE✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
    "TERA MAA #ROYAL KI FAN ",
    "TERI SEXY BAHEN KI CHUT OP✰♛𝐑𝐎𝐘𝐀𝐋♛✰➳𝐂𝐋𝐔𝐁✰
BRAND BAKI SB RAND",
]

GROUP = [-1001321613309, -1001749467927, -1001509154650, -1001355271574, -1001391516382, -1001569898907]


PORMS = [
        "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
        "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
        "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
        "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
        "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
        "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
        "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
        "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
        "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
        "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
        "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
        "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
        "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
        "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
        "https://telegra.ph/file/50637aa9c04d136687523.mp4",
        "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
        "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
        "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
        "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
        "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
        "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
        "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
        "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
        "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
        "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
        "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
        "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
        "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
        "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
        "https://telegra.ph/file/f483400ff141de73767ca.jpg",
        "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
        "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
        "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
        "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
        "https://telegra.ph/file/b434999287d3580250960.jpg",
        "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
        "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
        "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
        "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
        "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
        "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
        "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
        "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
        "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
        "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
        "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
        "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
        "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
        "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
        "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
        "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
        "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
        "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
        "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
]
